language: python
python:
- '3.6'
services: postgresql
env:
  global:
  - DJANGO_SETTINGS_MODULE="superlists.settings"
  - BUILD_ON_TRAVIS=true
  matrix:
  - DJANGO=1.11.3 DB=postgresql
addons:
#  firefox: "54.0.1"
  sauce_connect:
    username: "xiaoleATRI"
    access_key: "48d14f57-6c67-45cb-8775-f28c7fe7e56f"
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.18.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - psql -c "CREATE DATABASE xiaole;" -U postgres
  - psql -c "CREATE USER xiaole WITH CREATEUSER PASSWORD 'Besthuaihua@22';" -U postgres
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  # python manage.py migrate
  # python manage.py test lists/
  # python manage.py test functional_tests/
  # - coverage run --source=./ manage.py test lists/
  - coverage run --source=./ --omit=*/migrations/*,lists/apps.py,lists/__init__.py,manage.py,functional_tests/__init__.py,superlists/wsgi.py, manage.py test
after_success:
  coveralls
before_deploy: "echo 'ready?'"
deploy:
  provider: heroku
  buildpack:
    - python
    - https://github.com/agriffis/nginx-buildpack.git
  api_key:
    secure: qLJSp2ZQo2xyJnZD9b92Zm9x2EdudSBzD2JoVgYwnCpOIdLoUubF2ggKxxebH3/cpnaa78jzfRTpBDVkGHHhudlfwC0cA8MzC939oXAGBhV+c7JhS8/LkbKLSXq0Df+IsbD2F+MHA5bdwNwxoUSJ0Y4NOIbRHVKWxA5My6zeA/nBNojeFToDVxi+O7jyYrwc899fn0I95dZJoXK74l2QPJCEmGcsDbjBsC/6/uqZvRz2f/kkLKqaZofhZ6g+5d0yRABlig4KJNaXMyObarQcbyT2FqEdjY+KU4j44phnaIhWwFLgCdsHoFLjokeb1esW9fkIrlI9OdMEKraKTSUwde2zNtwXAMNa03gsy/xACyYAxl3wgfX9aANqxo57tFWvk9tsHPstvsgPYf0Ws7OVzbJf0DCkVGnmGuxiNNLqk3t+pynH235exk+Yq64aALdCCED0f7EPZKnicaUmMqLg9e4/6F9xQw7QTZkiboqw5yMApcEv1DZ9knXhX682MwODhW1MBAZlx1opo56JlT1QEQ/GhljTrFobQ9EHbzb00yM57aTr/bxc8whRwIKXjuOmmLXiI0WT67TxnJnPkBmJeW+pJof2T5DBCOYfnFa+12mB/zIVdyduOmbJYn6dwwfVsu4Po1oRt0ikCY0+yLnR1hWHIchmSod40FMEE+To878=
  strategy: git
  app: tddtraining
  on:
    repo: xiaoleATRI/TDD_Tutorial
    branch: lx_ICTRAINING-21_tdd
